name: Kernel.SendGrid CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
    - "**/.github/**"
    - "**/.editorconfig"
    - "**/README.md"
    - "**/templates/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --filter "FullyQualifiedName!~Integration"
            
